# Generated by Django 4.2.1 on 2023-05-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='course',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python3'), ('C', 'C'), ('C++', 'C++'), ('Django', 'Django')], default='Others', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='mailid',
            field=models.EmailField(max_length=254, verbose_name='Enter Mail id'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Enter Name'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.IntegerField(help_text='Mobile number should contain 10 digits', verbose_name='Enter Mobile Number'),
        ),
    ]
