# Generated by Django 4.2.1 on 2023-05-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_enquiry_course_alter_enquiry_mailid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdId', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('course', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C', 'C'), ('C++', 'C++'), ('Django', 'Django'), ('Full Stack', 'Full Stack')], max_length=20)),
                ('fees', models.IntegerField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Yet to Start', 'Yet to Start'), ('Hold', 'Hold'), ('Discontinued', 'Discontinued')], max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
